import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use("ggplot")
df=pd.read_csv("trains.csv")
print(df.head(10))
print(df.shape)
print(df.size)
print(df.dtypes)
print(df.info())
df["Order Date"]=pd.to_datetime(df["Order Date"],format="%d/%m/%Y")
df["Ship Date"]=pd.to_datetime(df["Ship Date"],format="%d/%m/%Y")
df=df.dropna()
df.duplicated().sum()
df = df.drop_duplicates()
print(df["Sub-Category"].value_counts())
print("-"*59)
print(df["Category"].value_counts())
print("-"*59)
sales_by_category=df.groupby("Category")["Sales"].sum().sort_values(ascending=False)
print("Total Sales in Category: ",sales_by_category)
print("-"*59)
sales_by_Country=df.groupby("Country")["Sales"].sum().sort_values(ascending=False)
print("Total Sales in Country :",sales_by_Country)
print("-"*59)
sales_by_City=df.groupby("City")["Sales"].sum().sort_values(ascending=False)
print("Total Sales in City:",sales_by_City)
print("-"*59)
sales_by_ProductName=df.groupby("Product Name")["Sales"].sum().sort_values(ascending=False)
print("Total Sales in Product Name:",sales_by_ProductName)
print("-"*59)
print("Total Sales:", df["Sales"].sum())
print("-"*59)
sales_by_category.plot(kind='bar')
plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
plt.savefig
df['Month'] = df['Order Date'].dt.to_period('M')
monthly_sales = df.groupby('Month')['Sales'].sum()
monthly_sales.plot(kind="line")
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.tight_layout()
plt.show()
plt.savefig
profit_by_region=df.groupby("Region")["Sales"].sum()
# profit_by_region.plot(kind='pie')
plt.pie(profit_by_region,autopct="%1.1f%%",shadow=True,startangle=180,wedgeprops={"edgecolor":"black"})
plt.legend()
plt.title("Profit by Region")
plt.xlabel("Region")
plt.ylabel("Total Profit")
plt.tight_layout()
plt.show()
plt.savefig
